"""
subagents.py
─────────────────────────────────────────────────────────────────────────────
Specialist sub-agents for the Deep Agents orchestrator.

Sub-agent roster
─────────────────
1. table_agent — Structured data specialist: tables, CSV, XLSX
2. image_agent — VLM caption + picture classification specialist
3. code_agent  — Code / formula specialist running in a Docker sandbox
"""

from __future__ import annotations

import logging

from deepagents import create_deep_agent, CompiledSubAgent
from langchain_core.tools import tool
from langchain_ollama import ChatOllama

from store import retrieve_chunks, search
from sandbox import DockerSandbox, make_execute_tool, make_upload_tool

logger = logging.getLogger(__name__)


def get_llm() -> ChatOllama:
    return ChatOllama(
        model="minimax-m2.7:cloud",
        base_url="http://localhost:11434",
        temperature=0,
    )


@tool
def retrieve_table_chunks(query: str, top_k: int = 4) -> str:
    """
    Search the knowledge base specifically for table and structured data chunks.

    Parameters
    ----------
    query : Natural language question about data, numbers, or comparisons.
    top_k : Number of results (default 4).
    """
    chunks = search(query=query, top_k=top_k, content_type="table")

    if not chunks:
        return "No table chunks found for this query."

    lines = []
    for i, c in enumerate(chunks, 1):
        lines.append(
            f"[Table {i}] Source: {c.doc_source} | Pages: {c.page_numbers}\n"
            f"{c.text[:600]}\n"
        )
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 2. Table sub-agent
# ─────────────────────────────────────────────────────────────────────────────

TABLE_AGENT: dict = {
    "name": "table-agent",
    "description": (
        "Answers questions about structured data — tables, spreadsheets, "
        "CSV data, and numerical comparisons. Use when the user's question "
        "involves rows, columns, figures, statistics, or data analysis."
    ),
    "system_prompt": (
        "You are a structured data analyst specialising in document tables.\n\n"
        "Your workflow:\n"
        "1. Use retrieve_table_chunks() to find relevant table data.\n"
        "2. Analyse the data carefully — rows, columns, totals.\n"
        "3. Answer the question clearly with specific numbers and citations.\n"
        "4. Always mention the source document and page number.\n\n"
        "Output format:\n"
        "- Direct answer with figures\n"
        "- Supporting data from the table\n"
        "- Source citation\n"
        "Keep response under 400 words."
    ),
    "tools": [retrieve_table_chunks, retrieve_chunks],
}


# ─────────────────────────────────────────────────────────────────────────────
# Image tools
# ─────────────────────────────────────────────────────────────────────────────

@tool
def retrieve_picture_chunks(query: str, top_k: int = 4) -> str:
    """
    Search the knowledge base for picture and figure chunks, including VLM
    captions generated by the enrichment pipeline.

    Parameters
    ----------
    query : Question about a chart, diagram, figure, or visual element.
    top_k : Number of results.
    """
    chunks = search(query=query, top_k=top_k, content_type="picture")

    if not chunks:
        return "No picture chunks found. Ensure the document was ingested with image enrichment."

    lines = []
    for i, c in enumerate(chunks, 1):
        caption = c.extra_meta.get("caption", "(no caption)")
        lines.append(
            f"[Figure {i}] Source: {c.doc_source} | Pages: {c.page_numbers}\n"
            f"Caption: {caption}\n"
            f"Context: {c.text[:400]}\n"
        )
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 3. Image sub-agent
# ─────────────────────────────────────────────────────────────────────────────

IMAGE_AGENT: dict = {
    "name": "image-agent",
    "description": (
        "Answers questions about charts, figures, diagrams, and visual "
        "content extracted from documents. Use when the question involves "
        "a graph, plot, image, or any visual element."
    ),
    "system_prompt": (
        "You are a visual content analyst. Documents have been processed by "
        "a VLM pipeline that generated captions for all figures.\n\n"
        "Your workflow:\n"
        "1. Use retrieve_picture_chunks() to find relevant figure captions.\n"
        "2. Interpret the visual content from captions and context.\n"
        "3. Describe what the figure shows and answer the question.\n"
        "4. If no caption is available, say so — do not hallucinate.\n\n"
        "Output format:\n"
        "- What the figure shows\n"
        "- Direct answer to the question\n"
        "- Source citation (document + page)\n"
        "Keep response under 300 words."
    ),
    "tools": [retrieve_picture_chunks, retrieve_chunks],
}


# ─────────────────────────────────────────────────────────────────────────────
# Code sub-agent — CompiledSubAgent with Docker sandbox backend
# ─────────────────────────────────────────────────────────────────────────────

@tool
def retrieve_code_chunks(query: str, top_k: int = 4) -> str:
    """
    Search the knowledge base for code blocks and mathematical formulas
    extracted and enriched by Docling's code/formula enrichment pipeline.

    Parameters
    ----------
    query : Question about code, an algorithm, or a formula.
    top_k : Number of results.
    """
    code_chunks   = search(query=query, top_k=top_k // 2, content_type="code")
    formula_chunks = search(query=query, top_k=top_k // 2, content_type="formula")
    all_chunks = code_chunks + formula_chunks

    if not all_chunks:
        return "No code or formula chunks found for this query."

    lines = []
    for i, c in enumerate(all_chunks, 1):
        lang = c.extra_meta.get("code_language", "unknown")
        label = f"Code ({lang})" if c.content_type == "code" else "Formula (LaTeX)"
        lines.append(
            f"[{label} {i}] Source: {c.doc_source} | Pages: {c.page_numbers}\n"
            f"{c.text[:800]}\n"
        )
    return "\n".join(lines)


def build_code_agent() -> CompiledSubAgent:
    """
    Build the code sub-agent with a Docker sandbox as its execution backend.

    The sandbox is created fresh here. It will be stopped when the main
    agent session ends — the lifecycle is managed in agent.py.

    The code agent gets:
    - retrieve_code_chunks() to find extracted code/formulas from Docling
    - execute_in_sandbox() to run the code in the Docker container
    - upload_code_to_sandbox() to seed files before execution
    """
    sandbox = DockerSandbox.create(
        network_mode="none",    # No internet access inside container
        mem_limit="512m",
        cpu_quota=50_000,       # 50% of one CPU core
    )

    execute_tool = make_execute_tool(sandbox)
    upload_tool  = make_upload_tool(sandbox)

    code_agent_graph = create_deep_agent(
        model=get_llm(),
        tools=[retrieve_code_chunks, upload_tool, execute_tool],
        system_prompt=(
            "You are a code and mathematics specialist with access to an "
            "isolated Docker sandbox for safe code execution.\n\n"
            "Your workflow for code questions:\n"
            "1. Use retrieve_code_chunks() to find the relevant code/formula.\n"
            "2. Use upload_code_to_sandbox() to write it to /workspace/script.py.\n"
            "3. Use execute_in_sandbox() to run it and capture the output.\n"
            "4. If execution fails, debug and re-run (max 3 attempts).\n"
            "5. Return the result with a clear explanation.\n\n"
            "Your workflow for formula questions:\n"
            "1. Retrieve the LaTeX formula from retrieve_code_chunks().\n"
            "2. Convert it to a Python/sympy expression.\n"
            "3. Upload and execute in the sandbox.\n"
            "4. Return the numerical result and explain the formula.\n\n"
            "Output format:\n"
            "- Code or formula (quoted)\n"
            "- Execution result\n"
            "- Explanation\n"
            "- Source citation\n"
            "Keep response under 500 words."
        ),
    )

    return CompiledSubAgent(
        name="code-agent",
        description=(
            "Retrieves, runs, and explains code blocks and mathematical "
            "formulas extracted from documents. Executes code safely in an "
            "isolated Docker container. Use when the question involves "
            "code, algorithms, equations, or numerical computation."
        ),
        runnable=code_agent_graph,
    ), sandbox   # Return sandbox too so agent.py can manage its lifecycle


# ─────────────────────────────────────────────────────────────────────────────
# Sub-agent registry
# ─────────────────────────────────────────────────────────────────────────────

def build_all_subagents() -> tuple[list, list]:
    """
    Build and return all sub-agents plus any resources needing cleanup.

    Returns
    -------
    (subagents, resources)
        subagents : list to pass directly to create_deep_agent(subagents=...)
        resources : list of objects with a .stop() method (e.g. DockerSandbox)
    """
    code_agent, sandbox = build_code_agent()

    subagents = [
        TABLE_AGENT,
        IMAGE_AGENT,
        code_agent,
    ]

    resources = [sandbox]  # Will be stopped in agent.py finally block

    logger.info(
        "Sub-agents built: %s",
        [s["name"] if isinstance(s, dict) else s.name for s in subagents],
    )
    return subagents, resources
